import ProductsCard from "@/components/ProductsCard";
import Sidebar from "@/components/FiltersBar";
import { Metadata } from "next";

import React from "react";
import conncetToDB from "@/db/config/connectDB";
import User from "@/db/schema/product.schema";
export const metadata: Metadata = {
  title: "products | MY STORE",
  description: "Generated by create next app",
  icons: "./favicon.ico",
};
const Products = async ({ searchParams }: { searchParams: any }) => {
  // conncetToDB();
  // let result = await User.find();
  // console.log(result);

  return (
    <main className="px-6 mt-3 flex ">
      <Sidebar />
      <ProductsCard />
    </main>
  );
};

export default Products;
